language: c

script: asdf plugin-test grv $TRAVIS_BUILD_DIR "grv --version"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux

addons:
  apt:
    packages:
    - jq
